### ISSUE TITLE
Pre-rendered website does not work (?)

### ISSUE THREAD

**Issue by hartmut-co-uk** [Atinux/content-wind#10]
Hi, with a freshly created project from content-wind, generate, preview the pre-rendered website doesn't seem to work, though the generate step seems successful.

Is this a problem with content v2 or with this template?

Reproduce:
```
npx nuxi init my-website -t atinux/content-wind
cd my-website
yarn install
yarn generate
yarn preview
```
Now visit http://localhost:3000/about

The 'home' page flickers and then is re-rendered with some error:

<img width="796" alt="Screenshot 2022-06-06 at 12 08 59" src="https://user-images.githubusercontent.com/10864443/172141095-405ec306-76ad-4f8f-a03e-3767eb93bd43.png">

**Comment by Atinux** [comment]
I believe the `preview` command does not support static site generation so far, you can use the [serve](https://www.npmjs.com/package/serve) package on the `dist/` directory to preview.
