### ISSUE TITLE
rendering issue NITRO_PRESET=azure

### ISSUE THREAD

**Issue by sig9** [Atinux/content-wind#13]
I have noticed a rendering issue when a route is visited for the first time after a build with NITRO_PRESET=azure

Steps to reproduce:

``` bash
git clone git@github.com:Atinux/content-wind.git cw-issue
cd cw-issue
yarn
NITRO_PRESET=azure yarn build
npx @azure/static-web-apps-cli start .output/public --api-location .output/server
```
This should start the azure static web app cli on localhost:4280 which proxies requests to static pages and functions. 

When I navigate to localhost:4280 the / route renders nicely. Clicking About in the nav bar yields the results in the image below. Reloading http://localhost:4280/about shows the properly rendered /about route.

Alternately, if I first navigate to localhost:4280/about it will render nicely. Then clicking on the Home link in the nav bar shows raw json from the path="/" content query.

Seems to need a full reload on each route. I suspect there is some state preserved serverside because after all the routes have been hit once, I can open the pages in a different browser or incognito and the issue is no longer there.

I see this issue when running builds locally and also when builds are freshly deployed to azure static web apps.

![image](https://user-images.githubusercontent.com/2271605/173243128-b2c54b6d-3b24-4e45-b87d-5bf6a52a2601.png)

I'm guessing this might not be the right place to report this. I would appreciate any debug tips or redirects.

**Comment by Atinux** [comment]
Maybe @danielroe could guide you about the best place to debug.

**Comment by Atinux** [comment]
Closing here in the meantime

**Comment by sig9** [comment]
Studying Content and Nitro a bit before I open the ticket.
