### ISSUE TITLE
Excerpt displaying

### ISSUE THREAD

**Issue by ipatate** [Atinux/content-wind#17]
Hello, i don't find how to display the excerpt on a list of articles.
```
 <div v-for="article in articles" :key="article._path">
      <h2>{{ article.title }}</h2>
      <ContentRenderer :value="article" :excerpt="true" />
    </div>
```
this code display all the content of page : 
<img width="648" alt="Screenshot 2022-08-08 at 15 35 31" src="https://user-images.githubusercontent.com/46760/183430726-3338290e-a471-442e-85aa-10f82e49214e.png">

Thanks for help 👍🏼

**Comment by ipatate** [comment]
Not a good place for that. I move to nuxt/content repo. Sorry.

**Comment by Atinux** [comment]
No worries :blush:
