### ISSUE TITLE
Fresh install failed with 3 errors

### ISSUE THREAD

**Issue by ManasMadrecha** [Atinux/content-wind#18]
## Reproduction

1. Cloned the repo
2. `npm i`
3. `npm run dev`

## Errors in Terminal and the website doesn't show up

```
 ERROR  Missing "./dist/app/entry" export in "nuxt3" package

i Vite server using experimental vite-node...                                              

 ERROR  Missing "./dist/app/entry" export in "nuxt3" package

i @nuxt-themes/config-edge v0.0.1-27648855.385c9ae enabled!                                             
i Using Content Wind by Sebastien Chopin (@Atinux)                                                      
√ Design Tokens built in 120ms                                                                  

 ERROR  Rollup error:  Unexpected token (Note that you need plugins to import files that are not JavaScript)

√ Nitro built in 1503 ms
```

The localhost page is stuck on this: 
![image](https://user-images.githubusercontent.com/65993481/183437024-59cb1541-30ca-4939-b069-11dbebdb43e3.png)

And this error in Console: 

```
GET http://localhost:3000/ 503 (Server Unavailable)
```

**Comment by danielroe** [comment]
This issue should be resolved in nuxt [edge channel](https://v3.nuxtjs.org/guide/going-further/edge-channel/) and released shortly in RC.

**Comment by ManasMadrecha** [comment]
@danielroe That will be nice. However, doesn't this repo use `"nuxt": "npm:nuxt3@latest"` already?

**Comment by danielroe** [comment]
In that case, ensure you're using the latest release with `yarn upgrade` or `npm upgrade`.
