### ISSUE TITLE
[Question] Tailwind use

### ISSUE THREAD

**Issue by AdrianoCahete** [Atinux/content-wind#20]
The Tailwind use is because you don't know/want to work with css or do you have another why?

**Comment by Atinux** [comment]
Wow that's a though one :smile: 

I do plan to remove Tailwind but wanted to move fast to boostrap (lazy me)

**Comment by AdrianoCahete** [comment]
> I do plan to remove Tailwind but wanted to move fast to boostrap (lazy me)

I may help you with this (and because I don't like TW that much hahaha). What the expectations about this stylesheet?  
Need to be scss? Need to be on css custom variables (to be easy themed)?

**Comment by PatrikBird** [comment]
I really appreciate that you included tailwind in this template 👼

**Comment by Atinux** [comment]
The goal would be to move to https://design-tokens.nuxtjs.org directly, but this can be a fork since Content Wind is aimed to be used for Tailwind users.
