### ISSUE TITLE
Static deployment to github static resource js or css 404

### ISSUE THREAD

**Issue by iiemos** [Atinux/content-wind#23]
![image](https://user-images.githubusercontent.com/38515723/187648019-f36d89ae-a7bd-4469-975e-efaadd169b51.png)
![image](https://user-images.githubusercontent.com/38515723/187648053-886a0de1-7c98-4f4a-9089-e155451212ba.png)
Does yarn generate need any other configuration?

**Comment by Atinux** [comment]
It should work, did you add a `.nojekyll` in your `public/` directory?
