### ISSUE TITLE
How would I enable TailwindCSS Intellisense?

### ISSUE THREAD

**Issue by jjaimealeman** [Atinux/content-wind#27]
I ran `npx tailwindcss init` and it generates `tailwind.config.js`.

I put this in there:
```
/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./content/**/*.md"],
  theme: {
    extend: {},
  },
  plugins: [],
}
```
and expected TailwindCSS Intellisense to "just work", but it's not 🤔

Anyone have a solution?

**Comment by jjaimealeman** [comment]
In file `content/1.index.md`

If I enter some html like so `<a class="bg-emerald-500 text-3xl">test</a>` Intellisense works fine, 

but it doesn't work with `[test]{.text-gray-500.bg-orange-500.text-2xl}`

🤔

**Comment by Atinux** [comment]
Does it work with `[test]{class="text-gray-500"}`

Anyway I won't recommend to use Tailwind classes in the Markdown for better readability but use Component to wrap them.

Example:

```md
Welcome to my :highlight[Website]
```

**Comment by jjaimealeman** [comment]
Negative, this also does not bring up Intellisense.

`[test]{class="text-gray-500"}`

I will stick with your recommendation 👍
