### ISSUE TITLE
Can we add it as module to an existing project?

### ISSUE THREAD

**Issue by boussadjra** [Atinux/content-wind#29]
Can we add this as module in normal Nuxt project that has already setup content?

**Comment by Atinux** [comment]
It is made to be used with the `extends` feature actually.

But you can configure the `content` key in your `nuxt.config`, no need to add `@nuxt/content` to the `modules` key since this theme add it.

Do you have an example of what you want to achieve?

**Comment by boussadjra** [comment]
For example in Vitesse starter for Nuxt 3 
https://stackblitz.com/github/antfu/vitesse-nuxt3

**Comment by Atinux** [comment]
It is possible, but the risk here with vitesse-nuxt3 is that it uses another UI library (UnoCSS) where this template leverages TailwindCSS

**Comment by elonehoo** [comment]
@boussadjra 
It's really troublesome, but I like UnoCss very much, so I made one according to this repository
https://github.com/elonehoo/content-unocss

**Comment by Atinux** [comment]
Beautiful @elonehoo !

One thing, I updated content-wind to use `.demo/` to have `content/`, `public/` and `app.config.ts` inside.

I suggest doing the same 😊 
https://github.com/Atinux/content-wind/tree/main/.demo
