### ISSUE TITLE
wrong theme switcher behavior

### ISSUE THREAD

**Issue by asrvd** [Atinux/content-wind#32]
The current theme switcher button shows `Sun` icon when it's light mode and `Moon` icon when it's in dark mode, which is actually quite the opposite of how its supposed to behave. It should be `Moon` when it's in light mode and vice-versa.

![image](https://user-images.githubusercontent.com/68690233/198371833-f3b830ac-2751-41f2-bd19-cb95755e2a6a.png)
![image](https://user-images.githubusercontent.com/68690233/198371858-98d709f7-96d4-4a14-8e32-ef7c5c1cd1be.png)

Can open a PR if you feel like this needs to be fixed.

**Comment by Atinux** [comment]
Thank you for the feedback @asrvd 

Actually it is on purpose to show the current color-mode, multiple websites are doing the same.

See for example https://www.joshwcomeau.com/

**Comment by Atinux** [comment]
But you can anyway overwrite the `<ColorModeSwitch>` component by copying the code of https://github.com/Atinux/content-wind/blob/main/components/ColorModeSwitch.vue and creating `components/ColorModeSwitch.vue` in your project using content-wind to overwrite the theme component.
