### ISSUE TITLE
How can i modify the AppLayout.vue and AppNavBar.vue?

### ISSUE THREAD

**Issue by hermesalvesbr** [Atinux/content-wind#33]
Hi there,

Thanks for this project! 

I have installed the project with this command: 
`npx nuxi@latest init -t themes/content-wind my-website`

How can i customize the layout? This is possible?

**Comment by condorheroblog** [comment]
Hi @hermesalvesbr, I have some experience. I hope it can help you!

Create a new `AppLayout.vue` file under the components folder of your project, this file can overwrite the default layout. Currently, there are also `AppLayout vue`, `AppLoadingBar. vue`, `AppNavbar. Vue` and `ColorModeSwitch.vue` files that can be created.

See details here https://github.com/Atinux/content-wind/tree/main/components.

This is my example of imitating Anthony Fu's blog (https://antfu.me/posts) https://github.com/condorheroblog/condorhero.me/blob/main/components/AppLayout.vue

**Comment by hermesalvesbr** [comment]
Thanks for response. I tried with AppLayout.vue, but show me this error: 

`[plugin:vite:css] [postcss] /home/nuxt/site-assinador/components/AppLayout.vue?vue&type=style&index=0&lang.postcss:3:5: The `dark:` class does not exist. If `dark:` is a custom class, make sure it is defined within a `@layer` directive.`

**Comment by condorheroblog** [comment]
> Thanks for response. I tried with AppLayout.vue, but show me this error: 
> 
> `[plugin:vite:css] [postcss] /home/nuxt/site-assinador/components/AppLayout.vue?vue&type=style&index=0&lang.postcss:3:5: The `dark:` class does not exist. If `dark:` is a custom class, make sure it is defined within a `@layer` directive.`

You asked the right person. I also had this problem when I edited `AppLayout.vue` almost finished my homework, My solution is to copy the entire content of the content-wind's `AppLayout.vue` file to replace the local `AppLayout.vue`, then restart the development environment, the error is gone, and then restore the local file content.

I hope my advice can help you🥳

**Comment by Atinux** [comment]
@condorheroblog thank you for helping! Also I feel honoured that you use Content Wind for your personal website 😊 

Regarding the error when overwriting a component, I will see with the framework team but indeed restarting the server fixes it!

**Comment by hermesalvesbr** [comment]
![image](https://user-images.githubusercontent.com/379850/199580550-e7cd94e9-ad68-4d67-92f4-7ae3123ac391.png)

Didn´t work for me. I have tried:

1. rm -Rf .nuxt
2. rm -Rf node_modules
3. reboot my computer

:(

**Comment by Atinux** [comment]
Could you share your repo @hermesalvesbr ?

**Comment by hermesalvesbr** [comment]
This branch:

https://github.com/hermesalvesbr/content-wind/tree/wind 

Thank you for this attention.

**Comment by Atinux** [comment]
It works for me @hermesalvesbr 

![CleanShot 2022-11-03 at 14.23.27.png](https://volta.s3.fr-par.scw.cloud/Clean_Shot_2022_11_03_at_14_23_27_fb6fe92182.png)

**Comment by hermesalvesbr** [comment]
Perfect, i will try in another computer node-version.
