### ISSUE TITLE
Tailwind warn after upgrading to 0.4.0

### ISSUE THREAD

**Issue by bokub** [Atinux/content-wind#44]
Hi,

I have the following warning since I upgraded this module to version 0.4.0

![image](https://user-images.githubusercontent.com/17952318/209788001-89c8bb02-371b-4eae-ada8-214fc674476f.png)

Do you have any idea what the problem is ?

**Comment by Tahul** [comment]
Hello! :)

This is not a Tailwind warning, but it's coming from Pinceau!

Could you please share your lockfile, and try to upgrade it if you haven't done it recently?

This might be a version mismatch in tokens definition. :)

**Comment by bokub** [comment]
Hi,

These are the 2 versions of pinceau installed:

![image](https://user-images.githubusercontent.com/17952318/210607466-55baf260-7ed7-4a0c-8e9c-72c58abf453c.png)

**Comment by bokub** [comment]
Upgrading to `content-wind@0.4.1` fixed the issue :+1: 

![image](https://user-images.githubusercontent.com/17952318/210756408-ce6390a6-e310-4556-9307-1b9ad7c2ef78.png)
