### ISSUE TITLE
Development server is not starting properly

### ISSUE THREAD

**Issue by thetejasmagade** [Atinux/content-wind#60]
Development server is not starting properly.
In the browser it only shows nuxt's loading screen and in console "503 service unavailable"

![Screenshot 2023-04-01 172140](https://user-images.githubusercontent.com/53045273/229287060-560b8678-7881-4e27-9840-8eaeecf6912d.jpg)

**Comment by Atinux** [comment]
What is written in the console?

**Comment by thetejasmagade** [comment]
It's working fine now. I think my machine has some issue at that time. 🙌
