### ISSUE TITLE
Cannot start nuxt:  The requested module 'minimatch' does not provide an export named 'default'                                                         

### ISSUE THREAD

**Issue by pmcp** [Atinux/content-wind#64]
On install, and after running pnpm run dev i get the following error:

 ERROR  Cannot start nuxt:  The requested module 'minimatch' does not provide an export named 'default'                                                         

  import minimatch from 'minimatch';
  ^^^^^^^^^
  SyntaxError: The requested module 'minimatch' does not provide an export named 'default'
  at ModuleJob._instantiate (node:internal/modules/esm/module_job:124:21)
  at async ModuleJob.run (node:internal/modules/esm/module_job:190:5)

Am I doing something wrong?

**Comment by Atinux** [comment]
What version of pnpm are you using?

**Comment by Atinux** [comment]
Fixed by upgrading your dependencies
