### ISSUE TITLE
You need plugins to import files that are not JavaScript - from extends @nuxt-themes/elements components

### ISSUE THREAD

**Issue by derogate** [Atinux/content-wind#65]
I am trying to deploy to Github Actions by using components extended from @nuxt-themes/elements which are [Alert.vue](https://elements.nuxt.space/globals/alert), [List.vue](https://elements.nuxt.space/globals/list) & [CodeGroup.vue](https://elements.nuxt.space/globals/code-group) but got the following error in Gitthub Actions:

```
Error:  Unexpected token (Note that you need plugins to import files that are not JavaScript)
file: /home/runner/work/blog/blog/blog/node_modules/.pnpm/@nuxt-themes+elements@0.9.4/node_modules/@nuxt-themes/elements/components/globals/Alert.vue?vue&type=style&index=0&scoped=5ebafdf9&lang.ts?inline&used:1:0
1: .alert{margin-top:var(--space-8);margin-bottom:var(--space-8);border-radius:var(--radii-md);padding-left:var(--space-...
   ^
Error:  Unexpected token (Note that you need plugins to import files that are not JavaScript)
  at error (node_modules/.pnpm/rollup@3.21.7/node_modules/rollup/dist/es/shared/node-entry.js:2125:30)
  at Module.error (node_modules/.pnpm/rollup@3.21.7/node_modules/rollup/dist/es/shared/node-entry.js:13452:16)
  at Module.tryParse (node_modules/.pnpm/rollup@3.21.7/node_modules/rollup/dist/es/shared/node-entry.js:14163:25)
  at Module.setSource (node_modules/.pnpm/rollup@3.21.7/node_modules/rollup/dist/es/shared/node-entry.js:13765:39)
  at ModuleLoader.addModuleSource (node_modules/.pnpm/rollup@3.21.7/node_modules/rollup/dist/es/shared/node-entry.js:23730:20)
```

Running it locally renders the Vue components fine & also builds the static production build without any problem. 

Error happens while `npm run generate` in this context of Github Actions:
- Node v18.15.0
- pnpm v6
- Nuxt v3.4.3
- @nuxt/content v2.6.0
- @nuxt-themes/elements v0.9.4

**Comment by Atinux** [comment]
Could you try to add this in your nuxt.config:

```ts
export default defineNuxtConfig({
  experimental: {
    inlineSSRStyles: false
  }
})
```

**Comment by Atinux** [comment]
Could you try to use Nuxt 3.5 and remove the experimental flag @derogate ?

**Comment by derogate** [comment]
> Could you try to use Nuxt 3.5 and remove the experimental flag @derogate ?

Thanks for informing, just upgraded to Nuxt 3.5 & removed the experimental flag. Can build in Github Actions without error 👍
