### ISSUE TITLE
Inline code formatting issue

### ISSUE THREAD

**Issue by avxkim** [Atinux/content-wind#8]
Hello, there's an issue when i use back ticks to highlight inline code, there's a result:

![image](https://user-images.githubusercontent.com/5739191/171787291-e140458d-35da-476a-a58a-d54cd634b384.png)

Why back ticks are shown when being rendered? I didn't notice this in a playground: https://content.nuxtjs.org/playground/

Seems like it's happening only in this template. Also i've noticed usage of `:sparkles:` icons. Where i can check the full list of available icons?

**Comment by Aynh** [comment]
The back ticks seems to be tailwindcss typography thing, see [here](https://github.com/tailwindlabs/tailwindcss-typography/blob/289b2ba63d8382f5c127f4ba1a0775e2f1aacf26/src/styles.js#L1348) and [here](https://github.com/tailwindlabs/tailwindcss-typography/blob/289b2ba63d8382f5c127f4ba1a0775e2f1aacf26/src/styles.js#L1351).

And for the `:sparkles:` icons, you could use [this cheat sheet](https://github.com/ikatyang/emoji-cheat-sheet/blob/master/README.md).
