### ISSUE TITLE
The link to Navbar is incorrect.

### ISSUE THREAD

**Issue by ryoAccount** [Atinux/content-wind#82]
[1.index.md](https://github.com/Atinux/content-wind/blob/main/.demo/content/1.index.md?plain=1)

```
### Navigation

The navigation is generated from your pages, you can take a look at the [`<Navbar>`](https://github.com/Atinux/content-wind/blob/main/theme/components/Navbar.vue) component to see how it works.
```

When I access a link in the `<Navbar>` I get a 404.
Maybe the correct link destination is [AppNavbar.vue](https://github.com/Atinux/content-wind/blob/main/components/AppNavbar.vue)?

**Comment by Atinux** [comment]
Nice catch thank you!
