### ISSUE TITLE
Support code diffs & file names

### ISSUE THREAD

**Issue by heychazza** [Atinux/content-wind#9]
Hi,

It would be cool if this could support code diffs, like seen here:
<img width="598" alt="CleanShot 2022-06-03 at 11 55 05@2x" src="https://user-images.githubusercontent.com/47271716/171840986-8ecd4845-685f-471e-9fc4-d19348bb5f6c.png">

In addition to file names and tabs like:
![CleanShot 2022-06-03 at 11 56 46@2x](https://user-images.githubusercontent.com/47271716/171841173-c7a491d1-1cf9-4777-90c6-8635e8e3f862.png)
<img width="534" alt="CleanShot 2022-06-03 at 11 57 17@2x" src="https://user-images.githubusercontent.com/47271716/171841204-4ec0a502-1673-485c-af25-1ae3ec5910f6.png">

I wasn't sure if these are natively supported by Nuxt Content v2 already, and needed some form of syntax or flag. These are in the [docs](https://content.nuxtjs.org/guide/displaying/querying).

**Comment by Atinux** [comment]
Actually these components are part of Docus (docs generator) that we plan to open source during the following weeks.

**Comment by Atinux** [comment]
Actually for the diff, you need to use this syntax:

<pre>
```diff
- "nuxt": "latest"
+ "nuxt": "^3.0.0-rc.3"
```
</pre>

To activate it, update your `nuxt.config` to add it into the `preload`:

```ts
export default defineNuxtConfig({
  // ...
  content: {
    // ...
    highlight: {
      // ...
      preload: ['diff', 'ts'] // and other languages you need to highlight
    }
  }
})
```

**Comment by heychazza** [comment]
> Actually for the diff, you need to use this syntax:
> 
> 
> 
> <pre>
> 
> ```diff
> 
> - "nuxt": "latest"
> 
> + "nuxt": "^3.0.0-rc.3"
> 
> ```
> 
> </pre>
> 
> 
> 
> To activate it, update your `nuxt.config` to add it into the `preload`:
> 
> 
> 
> ```ts
> 
> export default defineNuxtConfig({
> 
>   // ...
> 
>   content: {
> 
>     // ...
> 
>     highlight: {
> 
>       // ...
> 
>       preload: ['diff', 'ts'] // and other languages you need to highlight
> 
>     }
> 
>   }
> 
> })
> 
> ```

So great, thank you!
