### ISSUE TITLE
How will you build the static files for this as a SPA?

### ISSUE THREAD

**Issue by MasterAkay** [atinux/content-wind#93]
How will you build the static files for this as a SPA?

I'm having trouble where the static files render but the markdown files are not found
<img width="877" alt="Screenshot 2024-02-29 at 9 58 44 PM" src="https://github.com/Atinux/content-wind/assets/32744161/0f4eb109-248e-4e7c-b047-a396730712ac">

**Comment by Atinux** [comment]
Do you have a reproduction?

**Comment by Sambuxc** [comment]
Please provide your file structure and configs
